theme: jekyll-theme-minimal
title: Yi-Chun (Rimi) Chen's Website
logo: /assets/self_draw.jpg
description: A PhD candidate at North Carolina State University, Computer Science. My research interests are Visual Narrative Comprehension and Generation.

