theme: jekyll-theme-minimal
title: Yi-Chun (Rimi) Chen's Website
description: I am a Ph.D. candidate at North Carolina State University, Computer Science. My research interests are Visual Narrative Comprehension and Generation. I am also an amateur comic artist who sometimes draws fan art.
logo: "/assets/selfrimi.JPG"
img: "/assets/selfsmall.JPG"
