theme: jekyll-theme-minimal
title: Yi-Chun (Rimi) Chen's Website
description: A PhD candidate at North Carolina State University, Computer Science. My research interests are Visual Narrative Comprehension and Generation.
logo: "/assets/selfrimi.JPG"
show_downloads: false
