theme: jekyll-theme-minimal
title: Yi-Chun (Rimi) Chen's Website
description: A Ph.D. candidate at North Carolina State University, Computer Science, ARNAV lab. Amateur comic artist.
logo: "/assets/selfsmall.jpg"

