theme: jekyll-theme-minimal
title: Yi-Chun (Rimi) Chen's Website
description: A Ph.D. in Computer Science @ North Carolina State University, ARNAV lab. Amateur comic artist.
logo: "/assets/photo.jpg"

